In [46]:
import numpy as np
from scipy.signal import convolve2d

In [2]:
np.dot([[0,0,0],[2,0,0],[1,0,0]],[[1,1,1],[1,-1,0],[-1,0,0]])

array([[0, 0, 0],
       [2, 2, 2],
       [1, 1, 1]])

In [5]:
a = np.array([[0,0,0],[2,0,0],[1,0,0]])
a

array([[0, 0, 0],
       [2, 0, 0],
       [1, 0, 0]])

In [6]:
b = np.array([[1,1,1],[1,-1,0],[-1,0,0]])
b

array([[ 1,  1,  1],
       [ 1, -1,  0],
       [-1,  0,  0]])

In [7]:
np.dot(a,b)

array([[0, 0, 0],
       [2, 2, 2],
       [1, 1, 1]])

In [8]:
c = np.array([[0,0],[2,0]])
d = np.array([[1,1],[1,-1]])

In [9]:
np.dot(c,d)

array([[0, 0],
       [2, 2]])

In [14]:
cn(c,d, mode = 'valid', method = 'direct')

array([[2]])

In [36]:
a = np.array([[2,3,2,4], 
     [3,1,2,2],
    [4,1,0,1],
    [7,2,1,3]])

In [39]:
b = np.array([[2,1],
             [1,3]])
c = b.T
c

array([[2, 1],
       [1, 3]])

In [40]:
cn(a,c, mode = 'valid')

array([[14, 16, 16],
       [16,  6, 10],
       [24,  7,  8]])

In [41]:
import scipy.signal as ss

In [42]:
ss.oaconvolve(a,b, mode = 'valid')

array([[14., 16., 16.],
       [16.,  6., 10.],
       [24.,  7.,  8.]])

In [ ]:
arr = np.array([[0, 0, 0],
                    [1, 1, 2],
                    [1, 3, 0]])

>>> kernel = np.array([[4, 1, 1],
                       [0, 3, 3],
                       [2, 1, 2]])

>>> from scipy.signal import convolve2d

>>> convolve2d(arr, kernel[::-1, ::-1])
array([[ 0,  0,  0,  0,  0],
       [ 2,  3,  7,  4,  4],
       [ 5, 13, 14, 12,  0],
       [ 4, 14, 16,  6,  8],
       [ 1,  4,  7, 12,  0]])

>>> convolve2d(arr, kernel[::-1, ::-1], 'valid')
array([[14]])

In [43]:
arr = np.array([[0, 0, 0],
                    [1, 1, 2],
                    [1, 3, 0]])

In [44]:
kernel = np.array([[4, 1, 1],
                       [0, 3, 3],
                       [2, 1, 2]])

In [47]:
convolve2d(arr, kernel[::-1, ::-1])

array([[ 0,  0,  0,  0,  0],
       [ 2,  3,  7,  4,  4],
       [ 5, 13, 14, 12,  0],
       [ 4, 14, 16,  6,  8],
       [ 1,  4,  7, 12,  0]])

In [49]:
convolve2d(arr, kernel[::-1, ::-1], 'same')

array([[ 3,  7,  4],
       [13, 14, 12],
       [14, 16,  6]])